import Link from "next/link";
import { HeroSection } from "../components/ui/HeroSection";
import { AbstractVisual } from "../components/ui/AbstractVisual";
import { SectionHeading } from "../components/ui/SectionHeading";
import { ProjectCard } from "../components/projects/ProjectCard";
import { featuredProjects } from "../data/projects";
import { ProcessSteps } from "../components/home/ProcessSteps";
import { ToolsList } from "../components/home/ToolsList";
import { CallToAction } from "../components/ui/CallToAction";
const areas = [["Educación", "Diseño experiencias de aprendizaje, recursos educativos, evaluaciones y procesos de formación práctica."], ["Tecnología", "Construyo prototipos, aplicaciones web y productos digitales con inteligencia artificial y tecnologías emergentes."], ["Audiovisual", "Desarrollo narrativas, guiones y piezas audiovisuales orientadas a comunicar ideas con claridad."], ["Arte", "Exploro composición, abstracción, textura y pensamiento visual como parte de mi proceso creativo."]];
export default function Home() { return <main><HeroSection eyebrow="Creative Technologist · Educator · Builder · Filmmaker" title="Transformo ideas complejas en experiencias visuales, educativas y digitales." text="Soy docente, builder y creador multidisciplinario. Trabajo en la intersección entre educación, inteligencia artificial, producto digital, comunicación audiovisual y tecnología." visual={<AbstractVisual variant="roma" large />} /><section className="section page-shell"><SectionHeading eyebrow="Posicionamiento" title="Una práctica, múltiples medios." intro="No separo educación, tecnología y creatividad. Utilizo cada disciplina como una herramienta para investigar, comunicar, enseñar y construir soluciones." /><div className="areas-grid">{areas.map(([title,text]) => <div className="area" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></section><section className="section page-shell"><SectionHeading eyebrow="Selección de trabajo" title="Proyectos que conectan ideas y acción." intro="Una muestra de proyectos educativos, tecnológicos, audiovisuales y artísticos." /><div className="project-grid">{featuredProjects.map(p => <ProjectCard key={p.slug} project={p} />)}</div><div className="section-more"><Link className="text-link" href="/projects">Ver todos los proyectos →</Link></div></section><section className="section dark-section"><div className="page-shell"><SectionHeading dark eyebrow="Método de trabajo" title="De una pregunta a una experiencia." intro="Trabajo con un ciclo sencillo que permite avanzar con criterio, construir rápido y aprender del resultado." /><ProcessSteps /></div></section><section className="section page-shell"><SectionHeading eyebrow="Caja de herramientas" title="Las herramientas siguen al problema." intro="Selecciono tecnologías y medios según el contexto, el propósito y las personas involucradas." /><ToolsList /></section><div className="page-shell"><CallToAction title="¿Construimos algo que valga la pena enseñar, ver o utilizar?" text="Estoy disponible para oportunidades en educación digital, inteligencia artificial, creación de contenidos, desarrollo de productos y proyectos interdisciplinarios." /></div></main>; }
